/*
 * This source file was generated by the Gradle 'init' task
 */
package com.gusmurphy.fun.aoc;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    static void main() {
        System.out.println(new App().getGreeting());
    }
}
